spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:postgresql://localhost:5432/shopsphere_user_dev
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    com.shopsphere: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

