version: '3.8'

services:
  
  mysql-db:
    environment:
      MYSQL_DATABASE: shipping_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  
  backend:
    build: ./shipping-service-folder-name 
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/shipping_db

  
  frontend:
    build: ./shopsphere-frontend-folder-name 
    ports:
      - "5173:80"
    depends_on:
      - backend