server:
  port: ${SERVER_PORT:3002}

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/productdb}
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

app:
  upload-dir: ${UPLOAD_DIR:/app/uploads}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
