package com.shopsphere.product.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap; // Added for Story 2.5.3
import java.util.List;
import java.util.Map; // Added for Story 2.5.3

@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "products") // For MongoDB
@org.springframework.data.elasticsearch.annotations.Document(indexName = "products") 
public class Product {
    
    @Id
    private String id;
    
    @Field(type = FieldType.Keyword)
    private String sellerId; 

    @Field(type = FieldType.Text, analyzer = "standard")
    private String name;
    
    @Field(type = FieldType.Text, analyzer = "standard")
    private String description;
    
    @Field(type = FieldType.Double)
    private Double price;

    @Field(type = FieldType.Keyword)
    private String categoryId;

    private Category category; 
    
    @Field(type = FieldType.Keyword)
    private String sku; 
    
    private List<String> images;
    
    private String primaryImage; 
    
    @Field(type = FieldType.Keyword)
    private String status; 
    
    @Field(type = FieldType.Keyword)
    private String brand;

    // --- Story 2.4.2 & 2.4.3: Visual Search Embedding & HNSW Optimization ---
    // Field to store the visual feature vector generated by ResNet (Dimensions: 512)
    // index = true and similarity = "cosine" enables optimized kNN search for large catalogs
    @Field(type = FieldType.Dense_Vector, dims = 512, index = true, similarity = "cosine")
    private List<Double> imageEmbedding;
    
    // --- Story 2.2.2: Product Variations ---
    private boolean hasVariations = false;
    
    @Field(type = FieldType.Nested)
    private List<ProductVariant> variants = new ArrayList<>();
    
    // --- Story 2.3.2: Rating & Reviews ---
    @Field(type = FieldType.Double)
    private Double averageRating = 0.0;
    
    @Field(type = FieldType.Integer)
    private Integer reviewCount = 0;

    // --- Story 2.5.3: Rating Breakdown ---
    // Stores the distribution of ratings (e.g., {"5": 120, "4": 45, "3": 10, "2": 2, "1": 5})
    private Map<String, Integer> ratingBreakdown = new HashMap<>();
    
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}