server:
  port: 3007

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/reviewdb}
    # Redis configuration updated for Spring Boot 3.x
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG # MongoDB queries balanna ona nam meka danna
    com.shopsphere.review: DEBUG # Oyaage code eke logs balanna
